# Generated by Django 4.2.11 on 2026-01-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='raw_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventdate',
            name='date_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='keyword',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='keyword',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='person',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='parsed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
