# Generated by Django 4.2.11 on 2026-01-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_article_raw_text_eventdate_date_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
