# Generated by Django 5.2.7 on 2025-10-30 15:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('theme', models.CharField(max_length=200, verbose_name='Исходная тематика')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Текстовый документ',
                'verbose_name_plural': 'Текстовые документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сессии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('algorithm_used', models.CharField(default='bayesian', max_length=100, verbose_name='Использованный алгоритм')),
                ('documents', models.ManyToManyField(to='text_analysis.textdocument', verbose_name='Анализируемые документы')),
            ],
            options={
                'verbose_name': 'Сессия анализа',
                'verbose_name_plural': 'Сессии анализа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200, verbose_name='Название темы')),
                ('topic_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None, verbose_name='Ключевые слова темы')),
                ('document_count', models.IntegerField(verbose_name='Количество документов')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Уверенность алгоритма')),
                ('documents', models.ManyToManyField(related_name='assigned_topics', to='text_analysis.textdocument', verbose_name='Документы в теме')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_results', to='text_analysis.analysissession', verbose_name='Сессия анализа')),
            ],
            options={
                'verbose_name': 'Результат тематического анализа',
                'verbose_name_plural': 'Результаты тематического анализа',
            },
        ),
    ]
